### ISSUE TITLE
your api key is leaked

### ISSUE THREAD

**Issue by lihugang** [GitHub30/deta-drive-proxy#1]
in your readme.md 
> API_KEY=c0m8f10j_uvveYTnAqUmVWCZ6oeCiJa9hoRPiSjif

**Comment by GitHub30** [comment]
Thanks for letting me know. I have been updated

**Comment by lihugang** [comment]
In fact, everyone can see the changes of this repository, you should delete your leaking api key in your project settings in Deta
@GitHub30

**Comment by lihugang** [comment]
and generate a new one for your project using

**Comment by GitHub30** [comment]
Sure thing. Thanks for your advice. 謝謝
